---
title: "Appendices"
---

```{r, libraries, echo=FALSE,warning=FALSE,message=FALSE}
# Packages to be used in the below document.

library("tidyverse")
library("kableExtra")


## I am choosing to use `kableExtra` for the tables. It makes for better PDF output tables as opposed to the `gt` package is better suited for HTML outputs.
```

# Appendix 1 -- Proposed Timeline

```{mermaid}
gantt
title Systematic Review Screening Timeline
dateFormat  YYYY-MM-DD


section  Corpus Training and Screening

Reviewer training I             :active, c1, 2023-03-14, 1d
Reviewer training II            :active, c2, 2023-03-21, 1d
Establising concordance         :crit, milestone, c3, after c2, 2d
Title/Abstract screening        :c4, after c3, 14d
Full-text screening             :c5, after c4, 14d
```



# Appendix 2 --  Databases and Search Terms

## Databases Searched

The following sections detail the databases search strategies implemented to extract citations and refererences in support of .

```{r, table3, warning=FALSE,message=FALSE}

t1 <- read_csv("data/a2table1.csv") %>%
  tibble()

gt1 <- kable(t1,
             col.names = c("Database Interface", "Database Name", "Date of Search", "Database Update", "Searchers")) %>%
  kable_styling(bootstrap_options = c("striped", "hover", "condensed", "responsive"), 
                font_size = 10) %>%
  add_header_above(
    c( "Databases Searched for CMM Systematic Review" = 5), 
    bold = TRUE)

 gt1

```


### MEDLINE Using PubMed


### Cochrane Library



# Appendix 3
